<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>sledzikBase</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>4b31e32f-b42f-4574-907b-12cc2a9d774f</testSuiteGuid>
   <testCaseLink>
      <guid>178910ba-faac-4828-8923-6ed37c9ccc2f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sledzik/sledzik_login</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>a2da6add-13f4-4ea3-b98e-0552fe5c8b02</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sledzik/glowna_switch</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d594de9-a982-4313-b11e-ff9c0117405d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7279aaf7-b08a-4d57-a5d2-9bf4ce7d8782</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e030f131-6171-4c7f-8239-0682fb994a8d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8aff5df6-57a9-4f31-a283-304bdae7d4a7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sledzik/filtr_moje</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
