<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>sledzikBase2</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>f2c89c30-c3ce-41dc-ab73-1d81bd0119f5</testSuiteGuid>
   <testCaseLink>
      <guid>178910ba-faac-4828-8923-6ed37c9ccc2f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sledzik/caselogin</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>19ff2fe7-c7b2-444a-928b-ea3350dd2efe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sledzik/sortVerify</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>a2da6add-13f4-4ea3-b98e-0552fe5c8b02</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sledzik/switchVerify</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d594de9-a982-4313-b11e-ff9c0117405d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7279aaf7-b08a-4d57-a5d2-9bf4ce7d8782</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e030f131-6171-4c7f-8239-0682fb994a8d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8aff5df6-57a9-4f31-a283-304bdae7d4a7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sledzik/filtrVerify</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbd5a331-5769-4a3e-a09f-b296c9d17950</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
