<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>list_dataZdarzenia</name>
   <tag></tag>
   <elementGuidId>b37be75c-b4b9-441c-bf06-864590db630c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;responsiveContent&quot;]/*[@id=&quot;eventDate&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class=&quot;responsiveContent&quot;]/*[@id=&quot;eventDate&quot;]</value>
   </webElementProperties>
</WebElementEntity>
